*** Variables ***

${PI_ProspectInformation}              xpath=/html/body/app-root/app-home/div/main/div[1]/div/div/app-prospect-creation-lcv/app-prospect-creation/div/form/mat-tab-group/mat-tab-header/div/div/div/div[1]
${PI_CustomerInformation}              xpath=/html/body/app-root/app-home/div/main/div[1]/div/div/app-prospect-creation-lcv/app-prospect-creation/div/form/mat-tab-group/mat-tab-header/div/div/div/div[2]
${PI_NegotiationModel}              xpath=/html/body/app-root/app-home/div/main/div[1]/div/div/app-prospect-creation-lcv/app-prospect-creation/div/form/mat-tab-group/mat-tab-header/div/div/div/div[3]
${PI_ProspectFollow-up}      xpath=/html/body/app-root/app-home/div/main/div[1]/div/div/app-prospect-creation-lcv/app-prospect-creation/div/form/mat-tab-group/mat-tab-header/div/div/div/div[4]
${PI_SalesConsultantName}               xpath=/html/body/app-root/app-home/div/main/div[1]/div/div/app-prospect-creation-lcv/app-prospect-creation/div/form/mat-tab-group/div/mat-tab-body[1]/div/app-prospect-information/div/div/form[1]/div[4]/div[1]/dx-select-box/div/div/div[1]/input
${PI_CustomerBase}       xpath=/html/body/app-root/app-home/div/main/div[1]/div/div/app-prospect-creation-lcv/app-prospect-creation/div/form/mat-tab-group/div/mat-tab-body[1]/div/app-prospect-information/div/div/form[1]/div[10]/div[1]/dx-select-box/div/div/div[1]/input
${PI_ProspectSource}       xpath=/html/body/app-root/app-home/div/main/div[1]/div/div/app-prospect-creation-lcv/app-prospect-creation/div/form/mat-tab-group/div/mat-tab-body[1]/div/app-prospect-information/div/div/form[1]/div[11]/div[1]/dx-select-box/div[1]/div/div[1]/input
${PI_TypeofPurchase}    xpath=/html/body/app-root/app-home/div/main/div[1]/div/div/app-prospect-creation-lcv/app-prospect-creation/div/form/mat-tab-group/div/mat-tab-body[1]/div/app-prospect-information/div/div/form[1]/div[12]/div[1]/dx-select-box/div/div/div[1]/input
${PI_TypeofUsage}    xpath=/html/body/app-root/app-home/div/main/div[1]/div/div/app-prospect-creation-lcv/app-prospect-creation/div/form/mat-tab-group/div/mat-tab-body[1]/div/app-prospect-information/div/div/form[1]/div[12]/div[2]/dx-select-box/div[1]/div/div[1]/input
${PI_ModelGroup}                    xpath=/html/body/app-root/app-home/div/main/div[1]/div/div/app-prospect-creation-lcv/app-prospect-creation/div/form/mat-tab-group/div/mat-tab-body[1]/div/app-prospect-information/div/div/form[1]/div[21]/div[1]/div[1]/dx-select-box/div/div/div[1]/input
${PI_SubModelGroup1}                    xpath=/html/body/app-root/app-home/div/main/div[1]/div/div/app-prospect-creation-lcv/app-prospect-creation/div/form/mat-tab-group/div/mat-tab-body[1]/div/app-prospect-information/div/div/form[1]/div[21]/div[1]/div[2]/dx-select-box/div[1]/div/div[1]/input
${PI_SubModelGroup2}                    xpath=/html/body/app-root/app-home/div/main/div[1]/div/div/app-prospect-creation-lcv/app-prospect-creation/div/form/mat-tab-group/div/mat-tab-body[1]/div/app-prospect-information/div/div/form[1]/div[21]/div[2]/div/dx-select-box/div/div/div[1]/input
${PI_Qty}                    xpath=/html/body/app-root/app-home/div/main/div[1]/div/div/app-prospect-creation-lcv/app-prospect-creation/div/form/mat-tab-group/div/mat-tab-body[1]/div/app-prospect-information/div/div/form[1]/div[21]/div[4]/div[1]/dx-text-box/div/div[1]/input
${PI_CustomerRequiredDeliveryDate}                    xpath=/html/body/app-root/app-home/div/main/div[1]/div/div/app-prospect-creation-lcv/app-prospect-creation/div/form/mat-tab-group/div/mat-tab-body[1]/div/app-prospect-information/div/div/form[1]/div[32]/div[1]/dx-date-box/div/div/div[1]/input
${PI_ExpectedDeliveryDate}                    xpath=/html/body/app-root/app-home/div/main/div[1]/div/div/app-prospect-creation-lcv/app-prospect-creation/div/form/mat-tab-group/div/mat-tab-body[1]/div/app-prospect-information/div/div/form[1]/div[32]/div[2]/dx-date-box/div/div/div[1]/input

${Ng_ModelGroup}                    xpath=/html/body/app-root/app-home/div/main/div[1]/div/div/app-prospect-creation-lcv/app-prospect-creation/div/form/mat-tab-group/div/mat-tab-body[3]/div/app-prospect-negotiation/form/div/div/div[1]/div[1]/dx-select-box/div[1]/div/div[1]/input
${Ng_ModelCode}                    xpath=/html/body/app-root/app-home/div/main/div[1]/div/div/app-prospect-creation-lcv/app-prospect-creation/div/form/mat-tab-group/div/mat-tab-body[3]/div/app-prospect-negotiation/form/div/div/div[1]/div[2]/dx-select-box/div[1]/div/div[1]/input
${Ng_ColorCode}                    xpath=/html/body/app-root/app-home/div/main/div[1]/div/div/app-prospect-creation-lcv/app-prospect-creation/div/form/mat-tab-group/div/mat-tab-body[3]/div/app-prospect-negotiation/form/div/div/div[2]/div[1]/dx-select-box/div[1]/div/div[1]/input
${Ng_OptionCodeDescription}                    xpath=/html/body/app-root/app-home/div/main/div[1]/div/div/app-prospect-creation-lcv/app-prospect-creation/div/form/mat-tab-group/div/mat-tab-body[3]/div/app-prospect-negotiation/form/div/div/div[2]/div[2]/dx-select-box/div/div/div[1]/input
${Ng_Qty}                    xpath=/html/body/app-root/app-home/div/main/div[1]/div/div/app-prospect-creation-lcv/app-prospect-creation/div/form/mat-tab-group/div/mat-tab-body[3]/div/app-prospect-negotiation/form/div/div/div[3]/div/dx-text-box/div/div[1]/input
${Ng_BookingDepositAmount_PerUnit}                    xpath=/html/body/app-root/app-home/div/main/div[1]/div/div/app-prospect-creation-lcv/app-prospect-creation/div/form/mat-tab-group/div/mat-tab-body[3]/div/app-prospect-negotiation/form/div/div/div[11]/div[2]/app-auto-easy-grid-cell-numeric-box/input
${Ng_PurchaseType}                    xpath=/html/body/app-root/app-home/div/main/div[1]/div/div/app-prospect-creation-lcv/app-prospect-creation/div/form/mat-tab-group/div/mat-tab-body[3]/div/app-prospect-negotiation/form/div/div/div[14]/div[1]/dx-select-box/div/div/div[1]/input
${Ng_TISCampaign1}                    xpath=/html/body/app-root/app-home/div/main/div[1]/div/div/app-prospect-creation-lcv/app-prospect-creation/div/form/mat-tab-group/div/mat-tab-body[3]/div/app-prospect-negotiation/form/div/div/div[27]/div[1]/div/dx-select-box/div/div/div[1]/input
${Ng_TISCampaign2}                    xpath=/html/body/app-root/app-home/div/main/div[1]/div/div/app-prospect-creation-lcv/app-prospect-creation/div/form/mat-tab-group/div/mat-tab-body[3]/div/app-prospect-negotiation/form/div/div/div[27]/div[2]/div/dx-select-box/div[1]/div/div[1]/input
${Ng_TISCampaign3}                    xpath=/html/body/app-root/app-home/div/main/div[1]/div/div/app-prospect-creation-lcv/app-prospect-creation/div/form/mat-tab-group/div/mat-tab-body[3]/div/app-prospect-negotiation/form/div/div/div[27]/div[3]/div/dx-select-box/div[1]/div/div[1]/input
${Ng_Checkbox_SubmitNegotiationforApproval}                    xpath=/html/body/app-root/app-home/div/main/div[1]/div/div/app-prospect-creation-lcv/app-prospect-creation/div/form/mat-tab-group/div/mat-tab-body[3]/div/app-prospect-negotiation/form/div/div/div[38]/div/dx-check-box/div/span
${Ng_Checkbox_GenerateBooking}      xpath=/html/body/app-root/app-home/div/main/div[1]/div/div/app-prospect-creation-lcv/app-prospect-creation/div/form/mat-tab-group/div/mat-tab-body[3]/div/app-prospect-negotiation/form/div/div/div[40]/div[1]/dx-check-box/div/span
${Ng_BookingDate}      xpath=/html/body/app-root/app-home/div/main/div[1]/div/div/app-prospect-creation-lcv/app-prospect-creation/div/form/mat-tab-group/div/mat-tab-body[3]/div/app-prospect-negotiation/form/div/div/div[41]/div[1]/dx-date-box/div/div/div[1]/input
${Ng_EstimateDeliveryDate}      xpath=/html/body/app-root/app-home/div/main/div[1]/div/div/app-prospect-creation-lcv/app-prospect-creation/div/form/mat-tab-group/div/mat-tab-body[3]/div/app-prospect-negotiation/form/div/div/div[41]/div[2]/dx-date-box/div/div/div[1]/input

${Fl_PlanNextFollow-upDate}                    xpath=/html/body/app-root/app-home/div/main/div[1]/div/div/app-prospect-creation-lcv/app-prospect-creation/div/form/mat-tab-group/div/mat-tab-body[4]/div/app-prospect-follow-up/form/div/div/div[1]/div[2]/dx-date-box/div/div/div[1]/input
${Fl_Follow-upChannel}                    xpath=/html/body/app-root/app-home/div/main/div[1]/div/div/app-prospect-creation-lcv/app-prospect-creation/div/form/mat-tab-group/div/mat-tab-body[4]/div/app-prospect-follow-up/form/div/div/div[1]/div[5]/dx-select-box/div[1]/div/div[1]/input
${Fl_Follow-upResult}                    xpath=/html/body/app-root/app-home/div/main/div[1]/div/div/app-prospect-creation-lcv/app-prospect-creation/div/form/mat-tab-group/div/mat-tab-body[4]/div/app-prospect-follow-up/form/div/div/div[1]/div[8]/dx-select-box/div/div/div[1]/input
${Fl_ProspectClosingProbability}                    xpath=/html/body/app-root/app-home/div/main/div[1]/div/div/app-prospect-creation-lcv/app-prospect-creation/div/form/mat-tab-group/div/mat-tab-body[4]/div/app-prospect-follow-up/form/div/div/div[2]/div[2]/dx-select-box/div[1]/div/div[1]/input
${btn_SavePS}                    xpath=/html/body/app-root/app-home/div/main/div[1]/div/div/div/div/app-screen-operations/p/span/dx-button
