name: Robot Framework Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Install Dependencies
        run: |
          pip install robotframework robotframework-seleniumlibrary selenium webdriver-manager

      - name: Run Robot Tests
        run: |
          # บน Linux เราต้องรันผ่าน Xvfb หรือมั่นใจว่าโค้ดใช้ --headless
          robot -d results tests/CreateNewCustomer_Ind_test.robot